# Generated by Django 6.1.1 on 2026-10-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_gallon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('coordinate_source', models.CharField(blank=True, choices=[('census_place', 'US Census Gazetteer place'), ('census_cousub', 'US Census Gazetteer county subdivision'), ('nominatim', 'Nominatim geocoder')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['state', 'city'], name='stations_fu_state_64a61f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_per_gallon__gt', 0)), name='fuel_price_positive')],
            },
        ),
    ]
